export const gameMenuList = [
  { title: "特码", to: "/games/tema" },
  { title: "正码", to: "/games/zhengma" },
  { title: "正码特", to: "/games/zhengma-te" },
  { title: "连码", to: "/games/lianma" },
  { title: "自选不中", to: "/games/zixuanbuzhong" },
  { title: "自选中一", to: "/games/zixuan-zhong-yi" },
  { title: "特平中", to: "/games/tepingzhong" },
  { title: "特码生肖", to: "/games/tema-zodiac" },
  { title: "连肖", to: "/games/lianxiao" },
  { title: "连肖不中", to: "/games/lianxiaobuzhong" },
  { title: "一肖项目", to: "/games/yi-xiao-xiangmu" },
  { title: "六肖", to: "/games/liu-xiao" },
  { title: "连尾", to: "/games/lianwei" },
  { title: "连尾不中 ", to: "/games/lianweibuzhong" },
  { title: "尾数项目", to: "/games/zhongshu-weishu" },
  { title: "一肖量", to: "/games/yi-xiao-laing" },
  { title: "一尾量", to: "/games/yi-wei-laing" },
  { title: "半波", to: "/games/banbo" },
  { title: "五行", to: "/games/wuhang" },
];
